In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
import warnings
warnings.filterwarnings("ignore")

In [26]:
loan_data = pd.read_csv("clean_data.csv")

In [27]:
loan_data.head()

,ID,Gender,Own_car,Own_property,Work_phone,Phone,Email,Unemployed,Num_children,Num_family,Account_length,Total_income,Age,Years_employed,Income_type,Education_type,Family_status,Housing_type,Occupation_type,Target
0,5008804,1,1,1,1,0,0,0,0,2,15,427500.0,32.868574,12.435574,Working,Higher education,Civil marriage,Rented apartment,Other,1
1,5008806,1,1,1,0,0,0,0,0,2,29,112500.0,58.793815,3.104787,Working,Secondary / secondary special,Married,House / apartment,Security staff,0
2,5008808,0,0,1,0,1,1,0,0,1,4,270000.0,52.321403,8.353354,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,Sales staff,0
3,5008812,0,0,1,0,0,0,1,0,1,20,283500.0,61.504343,0.000000,Pensioner,Higher education,Separated,House / apartment,Other,0
4,5008815,1,1,1,1,1,1,0,0,2,5,270000.0,46.193967,2.105450,Working,Higher education,Married,House / apartment,Accountants,0

In [28]:
loan_data.shape

(9709, 20)

In [29]:
loan_data.isnull().sum()

ID                 0
Gender             0
Own_car            0
Own_property       0
Work_phone         0
Phone              0
Email              0
Unemployed         0
Num_children       0
Num_family         0
Account_length     0
Total_income       0
Age                0
Years_employed     0
Income_type        0
Education_type     0
Family_status      0
Housing_type       0
Occupation_type    0
Target             0
dtype: int64

In [ ]:
X = loan_data.drop("Target", axis=1)
Y = loan_data["Target"]

In [35]:
X

,ID,Gender,Own_car,Own_property,Work_phone,Phone,Email,Unemployed,Num_children,Num_family,Account_length,Total_income,Age,Years_employed,Income_type,Education_type,Family_status,Housing_type,Occupation_type
0,5008804,1,1,1,1,0,0,0,0,2,15,427500.0,32.868574,12.435574,Working,Higher education,Civil marriage,Rented apartment,Other
1,5008806,1,1,1,0,0,0,0,0,2,29,112500.0,58.793815,3.104787,Working,Secondary / secondary special,Married,House / apartment,Security staff
2,5008808,0,0,1,0,1,1,0,0,1,4,270000.0,52.321403,8.353354,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,Sales staff
3,5008812,0,0,1,0,0,0,1,0,1,20,283500.0,61.504343,0.000000,Pensioner,Higher education,Separated,House / apartment,Other
4,5008815,1,1,1,1,1,1,0,0,2,5,270000.0,46.193967,2.105450,Working,Higher education,Married,House / apartment,Accountants
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9704,5148694,0,0,0,0,0,0,0,0,2,20,180000.0,56.400884,0.542106,Pensioner,Secondary / secondary special,Civil marriage,Municipal apartment,Laborers
9705,5149055,0,0,1,1,1,0,0,0,2,19,112500.0,43.360233,7.375921,Commercial associate,Secondary / secondary special,Married,House / apartment,Other
9706,5149729,1,1,1,0,0,0,0,0,2,21,90000.0,52.296762,4.711938,Working,Secondary / secondary special,Married,House / apartment,Other
9707,5149838,0,0,1,0,1,1,0,0,2,32,157500.0,33.914454,3.627727,Pensioner,Higher education,Married,House / apartment,Medicine staff
9708,5150337,1,0,1,0,0,0,0,0,1,13,112500.0,25.155890,3.266323,Working,Secondary / secondary special,Single / not married,Rented apartment,Laborers

In [34]:
for i in X.columns:

    print(X[i].dtype)
    if X[i].dtype == "str":
        print(i)

int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
float64
float64
float64
str
str
str
str
str

In [36]:
from sklearn.preprocessing import LabelEncoder
le  = LabelEncoder()
for col in X.select_dtypes(include="str").columns:
    X[col] = le.fit_transform(X[col])
X

,ID,Gender,Own_car,Own_property,Work_phone,Phone,Email,Unemployed,Num_children,Num_family,Account_length,Total_income,Age,Years_employed,Income_type,Education_type,Family_status,Housing_type,Occupation_type
0,5008804,1,1,1,1,0,0,0,0,2,15,427500.0,32.868574,12.435574,4,1,0,4,12
1,5008806,1,1,1,0,0,0,0,0,2,29,112500.0,58.793815,3.104787,4,4,1,1,17
2,5008808,0,0,1,0,1,1,0,0,1,4,270000.0,52.321403,8.353354,0,4,3,1,15
3,5008812,0,0,1,0,0,0,1,0,1,20,283500.0,61.504343,0.000000,1,1,2,1,12
4,5008815,1,1,1,1,1,1,0,0,2,5,270000.0,46.193967,2.105450,4,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9704,5148694,0,0,0,0,0,0,0,0,2,20,180000.0,56.400884,0.542106,1,4,0,2,8
9705,5149055,0,0,1,1,1,0,0,0,2,19,112500.0,43.360233,7.375921,0,4,1,1,12
9706,5149729,1,1,1,0,0,0,0,0,2,21,90000.0,52.296762,4.711938,4,4,1,1,12
9707,5149838,0,0,1,0,1,1,0,0,2,32,157500.0,33.914454,3.627727,1,1,1,1,11
9708,5150337,1,0,1,0,0,0,0,0,1,13,112500.0,25.155890,3.266323,4,4,3,4,8

In [37]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.svm import SVC
pipelines_std = {
    "LR_Std": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression()),
    ]),
    "RF_Std": Pipeline([
        ("scaler", StandardScaler()),
        ("model", RandomForestClassifier(n_estimators=100, random_state=42)),
    ]),
    "SVM_Std": Pipeline([
        ("scaler", StandardScaler()),
        ("model", SVC()),
    ]),
    "GB_Std": Pipeline([
        ("scaler", StandardScaler()),
        ("model", GradientBoostingClassifier()),
    ])
}

In [50]:
pipelines_MinMax = {
    "LR_MinMax": Pipeline([
        ("scaler", MinMaxScaler()),
        ("model", LogisticRegression()),
    ]),
    "RF_MinMax": Pipeline([
        ("scaler", MinMaxScaler()),
        ("model", RandomForestClassifier(n_estimators=100, random_state=42)),
    ]),
    "SVM_MinMax": Pipeline([
        ("scaler", MinMaxScaler()),
        ("model", SVC()),
    ]),
    "GB_MinMax": Pipeline([
        ("scaler", MinMaxScaler()),
        ("model", GradientBoostingClassifier()),
    ])
}

In [51]:
result = {}
all_pipelines = {**pipelines_std, **pipelines_MinMax}
all_pipelines

{'LR_Std': Pipeline(steps=[('scaler', StandardScaler()), ('model', LogisticRegression())]),
 'RF_Std': Pipeline(steps=[('scaler', StandardScaler()),
                 ('model', RandomForestClassifier(random_state=42))]),
 'SVM_Std': Pipeline(steps=[('scaler', StandardScaler()), ('model', SVC())]),
 'GB_Std': Pipeline(steps=[('scaler', StandardScaler()),
                 ('model', GradientBoostingClassifier())]),
 'LR_MinMax': Pipeline(steps=[('scaler', MinMaxScaler()), ('model', LogisticRegression())]),
 'RF_MinMax': Pipeline(steps=[('scaler', MinMaxScaler()),
                 ('model', RandomForestClassifier(random_state=42))]),
 'SVM_MinMax': Pipeline(steps=[('scaler', MinMaxScaler()), ('model', SVC())]),
 'GB_MinMax': Pipeline(steps=[('scaler', MinMaxScaler()),
                 ('model', GradientBoostingClassifier())])}

In [52]:
for name , pipe in all_pipelines.items():
    pipe.fit(X_train, Y_train)
    Y_pred = pipe.predict(X_test)
    acc = accuracy_score(Y_test, Y_pred)
    result[name] = acc
    print(f"{name} Accuracy: {acc}")

LR_Std Accuracy: 0.8542739443872297
RF_Std Accuracy: 0.8558187435633368
SVM_Std Accuracy: 0.8542739443872297
GB_Std Accuracy: 0.8553038105046344
LR_MinMax Accuracy: 0.8542739443872297
RF_MinMax Accuracy: 0.8558187435633368
SVM_MinMax Accuracy: 0.8542739443872297
GB_MinMax Accuracy: 0.8537590113285273